name: Rescan Application in CAST AIP

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Manual trigger from Actions tab

jobs:
  rescan:
    runs-on: self-hosted  # Use the self-hosted runner instead of windows-latest

    steps:
      # Step 1: Checkout the repository to the default location
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Copy repository to the target directory
      - name: Copy repository to target directory
        run: |
          Copy-Item -Path "C:\Users\RecipePortal_dotnet\RecipePortal_dotnet" -Destination "C:\Users\JKM\Documents\Cast_Software\G\SOURCES\RecipePortal_dotnet" -Recurse -Force

      # Step 3: List the contents of the checked-out repository in the target directory
      - name: List directory contents of repository
        shell: powershell
        run: Get-ChildItem -Path 'C:\\Users\\JKM\\Documents\\Cast_Software\\G\\SOURCES\\RecipePortal_dotnet'

      # Step 4: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 5: Verify network connectivity
      - name: Verify network connectivity
        run: |
          ping https://6460-60-243-239-67.ngrok-free.app  # Ping the server to check connectivity
          curl --head --fail --silent --show-error http://JKMLAP1:8081  # Check HTTP connectivity
          sleep 5  # Wait to ensure service is ready

      # Step 6: Rescan the application using CAST AIP CLI
      - name: Rescan Application
        run: |
          java -jar aip-console-tools-cli.jar add --apikey="pPk47wUp.lg90GFWe2R7X4oJFnIgW1FH5SGY0wkm9" -n "RecipePortal" --server-url="http://localhost:8081" --no-clone -f "C:\\Users\\JKM\\Documents\\Cast_Software\\G\\SOURCES\\RecipePortal_dotnet" --verbose=false --set-as-current=true --upload-application=true --process-imaging=true
