name: Rescan Application in CAST AIP

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Manual trigger from Actions tab

jobs:
  rescan:
    runs-on: windows-latest  # Use the latest Windows runner available

    steps:
      # Step 1: Checkout the repository to the default location
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Copy repository to target directory
      - name: Copy repository to target directory
        run: |
          Copy-Item -Path "D:\a\RecipePortal_dotnet\RecipePortal_dotnet" -Destination "C:\Users\JKM\Documents\Cast_Software\G\SOURCES\RecipePortal_dotnet" -Recurse -Force

      # Optional Step 3: Remove the original repository (if necessary)
      - name: Remove original repository directory
        run: |
          Remove-Item -Path "D:\a\RecipePortal_dotnet\RecipePortal_dotnet" -Recurse -Force

      # Step 4: List the contents of the checked-out repository
      - name: List directory contents of repository
        shell: powershell
        run: Get-ChildItem -Path 'C:\\Users\\JKM\\Documents\\Cast_Software\\G\\SOURCES\\RecipePortal_dotnet'
        
      # Step 4: List the contents of the 'Automation' directory (updated path for JAR)
      - name: List contents of Automation directory (JAR location)
        shell: powershell
        run: Get-ChildItem -Path 'C:\\Users\\JKM\\Documents\\Automation'  # Updated JAR directory path

      # Step 5: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 6: Verify network connectivity
      - name: Verify network connectivity
        run: |
          ping https://6460-60-243-239-67.ngrok-free.app  # Ping the server to check connectivity
          curl --head --fail --silent --show-error https://6460-60-243-239-67.ngrok-free.app  # Check HTTP connectivity

      # Step 7: Rescan the application using CAST AIP CLI
      - name: Rescan Application
        run: |
          java -jar aip-console-tools-cli.jar add --apikey="bkmj2aEO.vbrR4eMUZacrJYBLf5zBiH5leCc5mItA" -n "RecipePortal" --server-url="https://6460-60-243-239-67.ngrok-free.app" -f "C:\\Users\\JKM\\Documents\\Cast_Software\\G\\SOURCES\\RecipePortal_dotnet" --verbose=false --set-as-current=true --upload-application=true --process-imaging=true
